### ISSUE TITLE
Mixed chisquare distribution, dsumchisqpow with df=0

### ISSUE THREAD

**Issue by ghost** [shabbychef/sadists#1]
Great package!

I'm looking for the mixed chi-square distribution, esp. (1/4) \* chisq(0) + (1/2) \* chisq(1) + (1/4)*chisq(2).

Seems like I can get that one by using sumchisqpow with power all set to 1?

```
quantiles <- c(0.90, 0.95, 0.99)
wts <- c(1/4, 1/2, 1/4)
df <- c(0, 1, 2)
pow <- c(1, 1, 1)
dsumchisqpow(quantiles, wts, df, pow)
## Warning message:
## In lgamrat(a, b) : value out of range in 'lgamma'
```

The warning is due to df=0. chisq(0) is 0 with probability 1.

Can you have a look please?

**Comment by shabbychef** [comment]
A chi-square with df=0 is a Dirac delta at 0, I believe. While this should be valid input, and I will try to make it so, as a stopgap measure I suspect it can be checked by the user before calling `dsumchisqpow`.

**Comment by shabbychef** [comment]
It turns out that this is merely a warning when `lgamrat` is called with one argument zero. This calls `lgamma` with a zero argument, returning an `Inf` and throwing the warning. The computed value ends up correct in this case, so I suggest either trapping the warning or ignoring it altogether.

**Comment by ghost** [comment]
Thank you for having a look!
For my above example, I get `NaN`s as a result (forgot to put that into the original post, sorry). The critical values for the mixed distribution above should be 7.289, 4.321, 2.952 for sign.-levels 0.01, 0.05, 0.1 respectively. Any hint how I can get those and the full distribution?

**Comment by shabbychef** [comment]
The problem is that the fourth input to `dsumchisqpow` is `ncp` not `pow`. Maybe it should be reversed. (Also, you want `qsumchisqpow`, but that's a one character error). So I get:

``` r
quantiles <- c(0.90, 0.95, 0.99)
wts <- c(1/4, 1/2, 1/4)
df <- c(0, 1, 2)
pow <- c(1, 1, 1)
qsumchisqpow(quantiles, wts, df, pow=pow)
[1] 2.121 2.693 4.024
```

These do not seem to match your values. I will check them empirically:

``` r
rvs <- rsumchisqpow(10000,wts=wts[2:3],df=df[2:3],pow=pow[2:3])
quantile(rvs,c(0.9,0.95,0.99))
  90%   95%   99% 
2.129 2.776 4.093 
```

These are pretty close. The `rsumchisqpow` pukes on the 0 df summand, which _is_ a bug. I will file an issue for that. Maybe #3.

**Comment by shabbychef** [comment]
Given that your weights sum to 1, and your df are in integer order, I suspect you have confused this distribution with the chi-bar-square distribution (_c.f._ http://onlinelibrary.wiley.com/doi/10.1002/0471667196.ess0265.pub2/abstract ). The 'sum of chi-square power' distribution here is literally the (weighted) sum of independent non-central chi-square variates raised to some powers. The density is a convolution, not a sum. If you take the weighted sum of densities as the density, you get something like the chi-bar-square instead. Sorry for the confusion, but I think this should be clear in the documentation.

**Comment by ghost** [comment]
Thank you for refereing me to chi-bar-square and taking the time! The textbook called it just 'mixed chi-square' which is why I came here. In package `emdbook`, there is a chi-bar-square distr. implemented which is called in the help file 'mixed chi-square' distr. This seems to be what I am looking for. Unfortunately, `emdbook::qchibarsq` is limited to a mixture of 2 chi-sq variables with `df=(df, df-1)`. It does _not_ seem to support weighting of more than 2 variables...

At least, you found #3 by my question.

**Comment by ghost** [comment]
By looking at the source of `emdbook::pchibarsq`, I tried to extended that to my case:

```
crit <- c(7.289, 4.321, 2.952)
p.val <- (1/4)*pchisq(crit, df=0, lower.tail = F) + (1/2) * pchisq(crit, df=1, lower.tail = F) + (1/4) * pchisq(crit, df=2, lower.tail = F)
## 0.01000252 0.04763926 0.10002319
```

[4.321 could be a typo in the book or rounding error; 4.231 does way better
_EDIT:_ confirmed as typo]

That seems to be what I was looking for. However, it would be nice to have that as d, q, p, r functions. I think, it does not fit neatly for the interface of `emdbook::pchibarsq`, where only 2 variables are supported, not an arbitrary amount of variables.  Maybe you are interested in this distribution for your `sadists` package?
