### ISSUE TITLE
Can we use sadists to compute the k-square distribution?

### ISSUE THREAD

**Issue by dcousin3** [shabbychef/sadists#13]
Hello, Thanks for implementing the k-prime and lambda-prime distributions, this is very appreciated. I was wondering if you were planning to implement the k-square distribution as well?

**Comment by shabbychef** [comment]
hi,
I am interested in the k-square, but I probably would not implement it here, as the moments or cumulants would be hard to compute. Some time ago I had started work on a general K-prime implementation in [this repo](https://github.com/shabbychef/kprime). It will likely take some time, however.

**Comment by dcousin3** [comment]
Ok, let me know when you do. Denis.

**Comment by shabbychef** [comment]
I've made an issue in the `kprime` repo.  Are you interested in the density, or the distribution, or the quantile? (or all three?)

**Comment by dcousin3** [comment]
Hello,

The quantile will be my main use, but having the density is useful from times to times to have plots.

Thank you very much!

Denis.



De : Steven Pav [mailto:notifications@github.com]
Envoyé : 19 juin 2020 01:18
À : shabbychef/sadists
Cc : Denis Cousineau; State change
Objet : Re: [shabbychef/sadists] Can we use sadists to compute the k-square distribution? (#13)

Attention : courriel externe | external email

I've made an issue in the kprime repo. Are you interested in the density, or the distribution, or the quantile? (or all three?)
