### ISSUE TITLE
doubly non-central F distribution with df2 = 1

### ISSUE THREAD

**Issue by davidruegamer** [shabbychef/sadists#5]
I'm getting a warning and a NaN result when using the `pdnf`-function with `df2=1`. This is due to the fact, that in the `log.deno`-part in `dnf_moments` the function `chisq_moms` tries to calculate the logarithm of a negative value as `ReF11(orders + hadf, hadf, hancp)) = log(ReF11(-(1:order.max) + 0.5, 0.5 hancp)` in turns yields negative values (`ncp > 2` in my case, therefore `hancp > 1`).

If it is not an inherent problem of the specific distribution, I would be very greatful if you could fix the problem.

**Comment by shabbychef** [comment]
A MWE: 

```
library(sadists)
y <- sadists::pdnf(seq(0.1,0.9,by=0.1), df1 = 5, df2 = 1, ncp1=0.5, ncp2=0.25)
show(y)
```

This yields:

```
Warning messages:
1: In log(ReF11(orders + hadf, hadf, hancp)) : NaNs produced
2: In sqrt(raw.cumulants[2]) : NaNs produced

[1] NaN NaN NaN NaN NaN NaN NaN NaN NaN
```

I will look into this.

**Comment by shabbychef** [comment]
This is actually very tricky because the kth moment of a non-central F does not exist if `k >= 0.5 df2`. The package estimates the density and cumulative distribution via the moments, which cannot be computed in this case. Having a significant `ncp2` might mitigate this, I am not sure, but I suspect not. Perhaps a different approach is needed for this 'corner case'. I would consult Paolella's book _Intermediate Probability_. There does not seem to be an immediately obvious fix I can implement quickly to `pdnf`.

**Comment by shabbychef** [comment]
@davidruegamer Can you possibly abuse equation (1) from [Butler & Paolella](http://www.stat.colostate.edu/statresearch/stattechreports/Technical%20Reports/1999/99-6%20Butler%20Paolella.pdf)? This would make the most sense when computing the distribution function for a single `q` in `pdnf`. If so, this would be a weighted sums of (noncentral) chi-squares distribution, I believe, so use `psumchisqpow`.

**Comment by davidruegamer** [comment]
Thank you for your quick and detailed response. In the meantime I found out, that the doubly non-central F distribution is only a special case in my application and that in general I'm actually looking for the distribution of a weighted sum of chi-squared random variables, where the weights are allowed to be negative (or, alternatively, a ratio of sums of positively weighted chi-squared random variables). My problem goes back to an indefinite quadratic form in nonsingular normal random vectors as described in [Mohsenipour & Provost](http://math.ut.ee/acta/15-1/MohsenipourProvost1.pdf). 
So I tried `psumchisqpow`, as you suggested, but the results do not agree with my 'gold standard' nor with an approximation via random numbers from chi-squared distributions. Consider the following example, which also led to the original problem with `pdnf` (in this case, however, `q = 1`):

```
q = 0
wts = c(0.1843903, -0.1843903)
df = c(1,1)
ncp = c(-2.740510,  2.213504)^2
pow = 1
```

This yields

```
> psumchisqpow(q = 0, wts = wts, df = df, ncp = ncp, pow = 1)
[1] 0
```

whereas the approximation via random variables from the corresponding non-central chi-squared distributions result in `0.35699` and the gold standard is `0.35379`. However, as the original issue can be solved by using the `psumchisqpow`-function, as you suggested, this is rather another issue.

**Comment by shabbychef** [comment]
I do not think I can replicate this since I do not have `lambdas` or `b`. Also negative elements should not appear in `ncp`. Can you provide a MWE?

-------- Original message --------

**Comment by davidruegamer** [comment]
Thank you for your reply. I edited the post on GitHub immediately after posting (see above).

**Comment by shabbychef** [comment]
Sorry for the noise: I should never read and reply to issues in email on my phone, apparently. 

The elements of `ncp` must be positive. Please check your original problem.

**Comment by davidruegamer** [comment]
Right. Thanks. I forgot the `^2`. It must be `ncp = c(-2.740510,  2.213504)^2`.

**Comment by shabbychef** [comment]
With the edits you have made, I get 0.355586. Do you not?

**Comment by davidruegamer** [comment]
I do get 0.355586 as well... Sorry for the inconvenience. And thanks again for the help!

**Comment by shabbychef** [comment]
No problem.
